### ISSUE TITLE
Implement send invoke

### ISSUE THREAD

**Issue by slipo** [CityOfZion/NeoLink#13]
This was originally done here:
https://github.com/CityOfZion/NeoLink/blob/master/src/js/background.js#L344

Using a custom fork of neon-js:
https://github.com/phetter/neon-js/commit/18c1ec4a89e485d8cb7b24b36a63d7e68df1ed1d

We want to reimplement this in the React version of the app in the development branch. We want to continue using the CityOfZion neon-js branch so research needs to be done into whether it's currently possible to do this in neon-js v2 or if we can work with them to add it.

**Comment by slipo** [comment]
I'll take this one on. @snowypowers has given me tips on how to accomplish this.

**Comment by phetter** [comment]
The authorization piece in neolink appears to fail in the tests I ran. Please see the slack channel for extra details.
