### ISSUE TITLE
Popup should remember pane + form values after close + reopen

### ISSUE THREAD

**Issue by slipo** [CityOfZion/NeoLink#16]
To be implemented in the development branch in React.

**Comment by slipo** [comment]
This seems like a good options for this:
https://github.com/erikras/redux-form

**Comment by austinhinderer** [comment]
It seems like storing this info in the redux store is the right idea, but isn't the store destroyed when you close the pane?

It seems like saving the store to localStorage could be a solution. Chrome extensions provide a sandboxed version of localStorage which we could use for this.

**Comment by slipo** [comment]
I'm closing this. This is done. There are some forms that are not set to remember but we'll either remove those or redo them with the reredesign.
