### ISSUE TITLE
Implement config pane

### ISSUE THREAD

**Issue by slipo** [CityOfZion/NeoLink#17]
To be done in React in the development branch

**Comment by austinhinderer** [comment]
Is there a design which describes what is required for this?

**Comment by slipo** [comment]
no there's not. I'm added private net support currently which implements something here. A start at least.

**Comment by slipo** [comment]
Here's what I have currently:
<img width="310" alt="screen shot 2018-01-15 at 9 26 15 am" src="https://user-images.githubusercontent.com/327999/34946791-359c9f98-f9d6-11e7-896c-f15cc98d51e0.png">
<img width="313" alt="screen shot 2018-01-15 at 9 26 09 am" src="https://user-images.githubusercontent.com/327999/34946792-35b69bdc-f9d6-11e7-82fa-ac71797e7f1c.png">

**Comment by slipo** [comment]
This has been merged ... for now I think this is what we want in the config pane. Closing.
