### ISSUE TITLE
Unable to add token hashes for testnet

### ISSUE THREAD

**Issue by kinmya** [CityOfZion/NeoLink#174]
In order to test wallet, tried to access CTX from wallet, but there is no option to load token into the wallet so it doesn't show in my wallet.  Can user be allowed to add the token type to the wallet?  Easier than having to do it on dev side for each one?

**Comment by phetter** [comment]
Does your test wallet have CTX? 

Note: Please confirm as the assets should load dynamically. However, I have seen some variation in another tool that uses this same dynamic method. It could be the API or the asset code. I'll review and then address your questions/suggestion.

I'm moving this to higher priority.

Thanks

**Comment by kinmya** [comment]
Yes, CTX

**Comment by kinmya** [comment]
I moved to testing on the mainnet to see the tokens I needed for now.

**Comment by phetter** [comment]
Okay, just confirming here that you were able to see tokens when you went to main. My testing has shown some funny business around token display too - will follow up.

**Comment by phetter** [comment]
I verified this is not an issue; closing. 

Thank you.
