### ISSUE TITLE
Component refactor

### ISSUE THREAD

**Issue by austinhinderer** [CityOfZion/NeoLink#29]
I'd like to suggest a number of changes to the components. Please let me know if you have any thoughts on these suggestions.

- Many components outside the container directory are connecting to the redux store. Instead of connecting to the redux store from our components, we should rely on containers to connect to the store and pass the data down via props.
- Many components don't take advantage of the lifecycle, so they could be converted to stateless functional components.
- My understanding of container components it that they handle interaction with the redux store, then pass their data down to your components which actually render their HTML. This helps create a separation of concerns between stateful interactions and stateless rendering. It also helps compartmentalize your testing structures. Currently, most of the container components handle some form of their own rendering. My suggestion is to leave the container components in charge of talking to the store and passing data via props to other components which handle the actual HTML rendering.

**Comment by slipo** [comment]
These changes make sense to me

**Comment by slipo** [comment]
Other improvements:
* Use Flow
* Prop type checking

**Comment by phetter** [comment]
This has been implemented.
