### ISSUE TITLE
Investigate popWindow usage in popupBackground.js

### ISSUE THREAD

**Issue by austinhinderer** [CityOfZion/NeoLink#44]
There is a variable which takes the popWindow function, but doesn't seem to get used.

https://github.com/CityOfZion/NeoLink/commit/cd70c7a11801a505a8b2d31adb63e690512429ca#diff-2a1604f1b1909cbd4aaae982c673b9cdR34

We should investigate if this needs to be corrected, and if not, we should re-work it so that the method gets invoked when we want it.

**Comment by phetter** [comment]
Can we close this?

**Comment by phetter** [comment]
I'm closing this issue since the code has been refactored. Please let me know otherwise. Thanks
