### ISSUE TITLE
Isolate material components from CoZ components

### ISSUE THREAD

**Issue by austinhinderer** [CityOfZion/NeoLink#52]
The material design components expose their own css in components which breaks proper CSS Module isolation, and causes issues with component tests. We should isolate the material components behind our own API to prevent CSS Module conflicts and make it easy to update our code if we want to remove the material components later.

**Comment by slipo** [comment]
I'm actually considering just removing material components and styling on our own... Those components have caused a bunch of issues and now they're blocking writing tests for components that include them.

**Comment by slipo** [comment]
Nevermind. Got tests working so I'm OK with it again.

**Comment by phetter** [comment]
This is good to close, yeah?

**Comment by DalderupMaurice** [comment]
All material components are moved If I am not mistaken @phetter
