### ISSUE TITLE
Proposed NeoLink Design

### ISSUE THREAD

**Issue by FredrikOseberg** [CityOfZion/NeoLink#69]
Current Mockups for proposed NeoLink design:

<img width="177" alt="screen shot 2018-02-26 at 22 39 27" src="https://user-images.githubusercontent.com/16081982/36696986-104fffc8-1b46-11e8-801e-ab4383327289.png">

<img width="178" alt="screen shot 2018-02-26 at 22 39 34" src="https://user-images.githubusercontent.com/16081982/36696999-15396a92-1b46-11e8-878c-0e23f40275b2.png">
<img width="172" alt="screen shot 2018-02-26 at 22 39 40" src="https://user-images.githubusercontent.com/16081982/36697017-17c4e6b0-1b46-11e8-9523-f965a0f288d4.png">
<img width="177" alt="screen shot 2018-02-26 at 22 39 55" src="https://user-images.githubusercontent.com/16081982/36697022-1b23141c-1b46-11e8-9e0a-751e1becacf3.png">
<img width="178" alt="screen shot 2018-02-26 at 22 39 59" src="https://user-images.githubusercontent.com/16081982/36697029-1e4f9ee4-1b46-11e8-9e51-e5c5f0974e41.png">

<img width="178" alt="screen shot 2018-02-26 at 22 42 01" src="https://user-images.githubusercontent.com/16081982/36697105-62d75ee4-1b46-11e8-9c47-615d08c7b307.png">

<img width="176" alt="screen shot 2018-02-26 at 22 30 53" src="https://user-images.githubusercontent.com/16081982/36696747-60f40ede-1b45-11e8-80bb-24d41cc21fe2.png">
<img width="176" alt="screen shot 2018-02-26 at 22 31 05" src="https://user-images.githubusercontent.com/16081982/36696750-669401c8-1b45-11e8-9483-83abba589a31.png">
<img width="172" alt="screen shot 2018-02-26 at 22 31 10" src="https://user-images.githubusercontent.com/16081982/36696756-691cd92e-1b45-11e8-90b3-4196c2bee31f.png">
<img width="181" alt="screen shot 2018-02-26 at 22 31 16" src="https://user-images.githubusercontent.com/16081982/36696759-6c72223c-1b45-11e8-84c6-ec118410aae6.png">
<img width="177" alt="screen shot 2018-02-26 at 22 31 21" src="https://user-images.githubusercontent.com/16081982/36696763-6e62c024-1b45-11e8-9089-79dcc44f65ea.png">
<img width="175" alt="screen shot 2018-02-26 at 22 31 26" src="https://user-images.githubusercontent.com/16081982/36696769-725216c6-1b45-11e8-901b-20ce8d245700.png">
<img width="178" alt="screen shot 2018-02-26 at 22 31 35" src="https://user-images.githubusercontent.com/16081982/36696775-775a1358-1b45-11e8-81e9-cb39c8357e44.png">
<img width="179" alt="screen shot 2018-02-26 at 22 31 42" src="https://user-images.githubusercontent.com/16081982/36696780-7a825fb8-1b45-11e8-810a-95e3a7f0cb8d.png">
<img width="176" alt="screen shot 2018-02-26 at 22 31 51" src="https://user-images.githubusercontent.com/16081982/36696781-7d0761fc-1b45-11e8-8e57-23f805f74293.png">
<img width="172" alt="screen shot 2018-02-26 at 22 32 02" src="https://user-images.githubusercontent.com/16081982/36696804-88ee1b96-1b45-11e8-847b-ee9f7831934b.png">
<img width="176" alt="screen shot 2018-02-26 at 22 32 08" src="https://user-images.githubusercontent.com/16081982/36696808-8a9f92c6-1b45-11e8-82e6-da5f4b3afe95.png">
<img width="175" alt="screen shot 2018-02-26 at 22 32 14" src="https://user-images.githubusercontent.com/16081982/36696811-8ced8fec-1b45-11e8-807e-84793c8526d7.png">
<img width="173" alt="screen shot 2018-02-26 at 22 32 22" src="https://user-images.githubusercontent.com/16081982/36696814-8e6be12a-1b45-11e8-893d-db7497eff124.png">
<img width="185" alt="screen shot 2018-02-26 at 22 32 28" src="https://user-images.githubusercontent.com/16081982/36696819-9029985e-1b45-11e8-89a7-d57b59d2e466.png">

**Comment by deanpress** [comment]
+1 @FredrikOseberg, @slipo, and me have coordinated and communicated for this redesign. Fredrik applied our feedback very efficiently to make a slick UI that corresponds with the features. 💯

**Comment by FredrikOseberg** [comment]
I'm currently working on implementing these @austinhinderer. Some of the pages are already done and live on the development branch.
