### ISSUE TITLE
can't build on windows10

### ISSUE THREAD

**Issue by QingmingZi** [CityOfZion/NeoLink#71]
os :widnows 10
nodejs:8.9.2
npm:5.5.1

PS D:\lab_git\NeoLink> npm run build

> NeoLink@0.1.29 build D:\lab_git\NeoLink
> NODE_ENV=production node utils/build.js

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NeoLink@0.1.29 build: `NODE_ENV=production node utils/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the NeoLink@0.1.29 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TerryLiu\AppData\Roaming\npm-cache\_logs\2018-02-28T06_05_56_735Z-debug.log

2018-02-28T06_05_56_735Z-debug.log
-----------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.5.1
3 info using node@v8.9.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle NeoLink@0.1.29~prebuild: NeoLink@0.1.29
6 info lifecycle NeoLink@0.1.29~build: NeoLink@0.1.29
7 verbose lifecycle NeoLink@0.1.29~build: unsafe-perm in lifecycle true
8 verbose lifecycle NeoLink@0.1.29~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\lab_git\NeoLink\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\OpenVPN\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;C:\Program Files (x86)\OpenSSH\bin;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Program Files\Java\jdk1.8.0_131\jre\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Git\cmd;C:\Users\TerryLiu\.app\;C:\Users\TerryLiu\AppData\Local\Microsoft\WindowsApps;D:\我的坚果云\代码库\neo-compiler\neon\bin\Release\netcoreapp1.0\win10-x64;C:\Users\TerryLiu\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\TerryLiu\AppData\Local\Yarn\bin
9 verbose lifecycle NeoLink@0.1.29~build: CWD: D:\lab_git\NeoLink
10 silly lifecycle NeoLink@0.1.29~build: Args: [ '/d /s /c', 'NODE_ENV=production node utils/build.js' ]
11 silly lifecycle NeoLink@0.1.29~build: Returned: code: 1  signal: null
12 info lifecycle NeoLink@0.1.29~build: Failed to exec build script
13 verbose stack Error: NeoLink@0.1.29 build: `NODE_ENV=production node utils/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid NeoLink@0.1.29
15 verbose cwd D:\lab_git\NeoLink
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.9.2
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error NeoLink@0.1.29 build: `NODE_ENV=production node utils/build.js`
22 error Exit status 1
23 error Failed at the NeoLink@0.1.29 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by slipo** [comment]
fixed!

**Comment by Ray-77** [comment]
> Executing task: npm run build <


> NeoLink@0.1.29 build C:\Users\Grace\Desktop\sendeo
> cross-env NODE_ENV=production node utils/build.js

'cross-env' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NeoLink@0.1.29 build: `cross-env NODE_ENV=production node utils/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the NeoLink@0.1.29 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Grace\AppData\Roaming\npm-cache\_logs\2018-03-23T03_50_07_054Z-debug.log
